sonar.projectKey=buscaminas-tripartito
sonar.projectName=Buscaminas Tripartito
sonar.sourceEncoding=UTF-8
sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.sonar/**,**/.scannerwork/**
